# -*- coding: utf-8 -*-
"""Medimatch Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rbC16d6tU5tmjnZuLio59vuao-PXFmbG

Yasmin Mohamed

# MediMatch Search Engine Design

**Section 1 - Installing and Importing Necessary Libraries**: This phase puts in place the Python environment using Python Terrier (PyTerrier), a complete toolkit for building information retrieval systems, and Pandas, a library for statistics manipulation and evaluation.

**Section 2 - Creating our Dataset**: It shows the process of collecting and organizing the health-associated information, which incorporates statistics about ddiseases, symptoms, and possible precautions, from variable sources for the foundational dataset for the MediMatch Search Engine.

**Section 3 - Data Preprocessing**: This component elaborates the preprocessing of the  dataset to make sure it has the correct format for indexing and retrieval.

**Section 4 - Enriching Results to Provide Additional Information**: This describes how the search engine's results are enriched with statistics like certain disorder descriptions and  precautions.

**Section 5 - Demonstration of MediMatch**: This final segment showcases the MediMatch Search Engine in action, demonstrating how customers can input signs and receive relevant disorder matches  illustrating the engine's functionality to resource information retrieval.

# Section 1 - Installing and Importing Necessary Libraries


**Python Terrier (Pyterrier)**
"""

!pip install python-terrier
import pyterrier as pt

pt.init()

"""**Pandas**"""

!pip install pandas
import pandas as pd

"""# Section 2 : Creating our Dataset"""

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/HealthSearchEngineData/dataset.csv'

df = pd.read_csv(file_path)

df_descriptions = pd.read_csv('/content/drive/My Drive/HealthSearchEngineData/disease_description.csv')
df_precautions = pd.read_csv('/content/drive/My Drive/HealthSearchEngineData/disease_precaution.csv')
df_severity = pd.read_csv('/content/drive/My Drive/HealthSearchEngineData/symptom_severity.csv')
df_training = pd.read_csv('/content/drive/My Drive/HealthSearchEngineData/Training.csv')
df_testing = pd.read_csv('/content/drive/My Drive/HealthSearchEngineData/Testing.csv')

"""# Section 3 - Data preprocessing"""

# List of symptom columns in dataset
symptom_columns = [col for col in df.columns if 'Symptom_' in col]


df['text'] = df[symptom_columns].apply(lambda x: ' '.join(x.dropna()), axis=1)

df['docno'] = df.index.astype(str)

df[['text', 'docno']].head()

"""**Indexing using Pyterrier**"""

from pyterrier.index import IterDictIndexer

index_path = "/content/drive/My Drive/HealthSearchEngineData/my_index"

indexer = IterDictIndexer(index_path, overwrite=True)
index_ref = indexer.index(df[['docno', 'text']].to_dict(orient='records'))

"""**Retrival and ranking**"""

from pyterrier import BatchRetrieve


index = pt.IndexFactory.of(index_ref)

BM25_retriever = BatchRetrieve(index, wmodel="BM25")


query = "vomiting high_fever headache"
results = BM25_retriever.search(query)
print(results)

"""# Section 4 - Enriching Results to  provide additional information

"""

print(df_training.columns)

results['docno'] = results['docno'].astype(int)


disease_mapping = df['Disease'].to_dict()


results['Disease'] = results['docno'].map(disease_mapping)


print(results[['docno', 'Disease']])

description_mapping = df_descriptions.set_index('Disease')['Symptom_Description'].to_dict()
results['Description'] = results['Disease'].map(description_mapping)


for i in range(4):
    precaution_col = f'Symptom_precaution_{i}'
    precaution_mapping = df_precautions.set_index('Disease')[precaution_col].to_dict()
    results[precaution_col] = results['Disease'].map(precaution_mapping)

print(results[['docno', 'Disease', 'Description', 'Symptom_precaution_0', 'Symptom_precaution_1', 'Symptom_precaution_2', 'Symptom_precaution_3']])

print(df_descriptions.head())

import pandas as pd
import pyterrier as pt
if not pt.started():
    pt.init()

print(df_precautions.columns)

precaution_columns = [col for col in df_precautions.columns if col.startswith('Precaution')]
for i, col in enumerate(precaution_columns, start=0):
    precaution_mapping = df_precautions.set_index('Disease')[col].to_dict()
    results[f'Symptom_precaution_{i}'] = results['Disease'].map(precaution_mapping)

for i in range(4):
    precaution_col = f'Symptom_precaution_{i}'
    precaution_mapping = df_precautions.set_index('Disease')[precaution_col].to_dict()
    results[precaution_col] = results['Disease'].map(precaution_mapping)

print(results[['Disease', 'Symptom_precaution_0', 'Symptom_precaution_1', 'Symptom_precaution_2', 'Symptom_precaution_3']].head())

print(df_descriptions.columns)

description_mapping = df_descriptions.set_index('Disease')['Symptom_Description'].to_dict()
results['Description'] = results['Disease'].map(description_mapping)


print(results[['Disease', 'Description', 'Symptom_precaution_0', 'Symptom_precaution_1', 'Symptom_precaution_2', 'Symptom_precaution_3']].head())

"""# Section 5 - Demonstration of MediMatch"""

index = pt.IndexFactory.of('/content/drive/My Drive/HealthSearchEngineData/my_index/data.properties')
def search_and_display(query):

    BM25_retriever = pt.BatchRetrieve(index, wmodel="BM25")
    results = BM25_retriever.search(query)


    results['docno'] = results['docno'].astype(int)

    disease_mapping = df['Disease'].to_dict()
    results['Disease'] = results['docno'].map(disease_mapping)

    description_mapping = df_descriptions.set_index('Disease')['Symptom_Description'].to_dict()
    results['Description'] = results['Disease'].map(description_mapping)

    for i in range(4):
        precaution_col = f'Symptom_precaution_{i}'
        precaution_mapping = df_precautions.set_index('Disease')[precaution_col].to_dict()
        results[precaution_col] = results['Disease'].map(precaution_mapping)

    display_columns = ['docno', 'Disease', 'Description', 'Symptom_precaution_0', 'Symptom_precaution_1', 'Symptom_precaution_2', 'Symptom_precaution_3']
    display(results[display_columns].head(10))

query = input("Enter symptom: ")
search_and_display(query)